# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

Vector:
*A vector is a one-dimensional array of numbers. It can be thought of as a list of elements, either arranged in a row (row vector) or a column (column vector).

*It has only one dimension, either a single row or a single column.

Matrix:
*A matrix is a two-dimensional array of numbers, typically organized into rows and columns.

*It has two dimensions: rows and columns.

**2. How to import `NumPy` library?** 

In [3]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [4]:
list_1 = [1,2,3,4,5]

In [9]:
# To avoid overwriting the output, please code here import numpy as np

# Given Python list
python_list = [1, 2, 3, 4, 5]

# Convert list to NumPy array
numpy_array = np.array(python_list)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [10]:
# To avoid overwriting the output, please code here 

# Generate array using arange()
arr = np.arange(6)

# Print the array
print("Generated Array:", arr)



Generated Array: [0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [11]:
# To avoid overwriting the output, please code here 

# Generate an array of 5 zeros
zeros_array = np.zeros(5)

# Print the array
print("Array of 5 zeros:", zeros_array)

Array of 5 zeros: [0. 0. 0. 0. 0.]


array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [17]:
# To avoid overwriting the output, please code here 

# Generate a matrix with 5 zeros
matrix = np.zeros((1, 5))

# Print the matrix
print(matrix)




[[0. 0. 0. 0. 0.]]


**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [18]:
# To avoid overwriting the output, please code here 

# Generate an array of five 1's
array_of_ones = np.ones(5)

# Print the array
print(array_of_ones)


[1. 1. 1. 1. 1.]


**8. Generate an array of "5" tens.**

In [19]:
# To avoid overwriting the output, please code here 

# Generate an array of five 10's
array_of_tens = np.full(5, 10)

# Print the array
print(array_of_tens)


[10 10 10 10 10]


**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [20]:
# To avoid overwriting the output, please code here 

# Generate an array of even numbers between 50 and 100 (exclusive)
even_numbers = np.arange(52, 100, 2)

# Print the array
print(even_numbers)


[52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [21]:
# To avoid overwriting the output, please code here 

# Generate an array of 10 linearly spaced points between 0 and 1
lin_space_array = np.linspace(0, 1, 10)

# Calculate the step size (difference between consecutive elements)
step_size = lin_space_array[1] - lin_space_array[0]

# Output the array and step size
print("Array:", lin_space_array)
print("Step size:", step_size)


Array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Step size: 0.1111111111111111


(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [22]:
# To avoid overwriting the output, please code here 

# Generate an array of 25 numbers
vector_array = np.arange(25)
print("Vector array:", vector_array)

# Convert vector array to 2-D matrix (5x5) using reshape
matrix_2d = vector_array.reshape(5, 5)
print("\n2-D Matrix using reshape:\n", matrix_2d)

# Modify the shape directly (though reshape is more explicit and better to use)
vector_array.shape = (5, 5)
print("\n2-D Matrix using shape attribute:\n", vector_array)


Vector array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

2-D Matrix using reshape:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

2-D Matrix using shape attribute:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
# To avoid overwriting the output, please code here 

# Generating the vector array
vector_array = np.arange(25)

# Convert the vector array into a 5x5 2-D matrix
matrix_2d = vector_array.reshape(5, 5)
print("2-D Matrix:\n", matrix_2d)


2-D Matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# To avoid overwriting the output, please code here 
# To check the current shape
print(vector_array.shape)  # Output: (25,)

# To reshape
vector_array.shape = (5, 5)  # Can reshape using shape, but not as flexible as reshape()
print(vector_array)


(25,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [28]:
# To avoid overwriting the output, please code here 

matrix = np.arange(25).reshape(5, 5)
print(matrix)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [29]:
# To avoid overwriting the output, please code here 

# Generate an array with linspace
array = np.linspace(0, 24, 25).reshape(5, 5)

# Print the array
print(array)


[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


**14. What is the main difference between `linspace()` and `arange()`?**

# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

arange():
Purpose:Generates values at regular intervals within a specified range.
Parameters:
Takes three arguments: start, stop, and step.
The step defines the increment between each value.
The values do not include the stop value.

linspace():
Purpose: Generates a specified number of evenly spaced points between a start and stop value.
Parameters:
Takes three arguments: start, stop, and num.
The num argument defines how many points to generate between the start and stop values.
The values include the stop value.

**15. How to generate a single random integer number using NumPy built-in function?**

In [32]:
# To avoid overwriting the output, please code here 

# Generate a random integer between 0 (inclusive) and 10 (exclusive)
random_integer = np.random.randint(0, 10)

print(random_integer)


2


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [33]:
# To avoid overwriting the output, please code here 

# Generate a 7x5 matrix of random numbers
random_matrix = np.random.rand(7, 5)

# Print the matrix without parentheses
for row in random_matrix:
    print(*row)


0.6241715521275529 0.26202236607658047 0.5988432879327382 0.05061734113222027 0.5194665786786817
0.23061925943122163 0.99024923754831 0.9971485504685519 0.2728933377270647 0.08567091405151239
0.9306477130301513 0.2126780461541542 0.5283887225605235 0.5499462647711568 0.28246279378081385
0.8702811767559624 0.527290202757344 0.10119308788589865 0.5682548588055518 0.9279613166356937
0.6779939330145172 0.2582616844713749 0.38795410873929514 0.380841709889024 0.47655106476444453
0.36688117843539314 0.6347950965186913 0.915031914273597 0.9476166235548609 0.2824975976251506
0.4003160434613615 0.906539130298944 0.27344837004999567 0.7647014410602674 0.41411005561483494


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [34]:
# To avoid overwriting the output, please code here 

# Generate a 7x7 identity matrix
identity_matrix = np.eye(7)

print(identity_matrix)


[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 